name: SonarCloud Backend
on:
  push:
    branches:
      - main # change it to your main branch.
      - branch-*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  user-service: # Change the job name to a backend microservice name.
    if: ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: BE user-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/user-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.USERSERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bootcamp-be-105-user-service -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} -Dsonar.pullrequest.key=${{github.event.pull_request.number}} # Change the projectName and projectKey accordingly.

  business-service: # Change the job name to a backend microservice name.
    if: ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: BE business-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/business-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.BUSINESS_SERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bootcamp-be-105-business-service -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} -Dsonar.pullrequest.key=${{github.event.pull_request.number}} # Change the projectName and projectKey accordingly.

  
  transaction-service: # Change the job name to a backend microservice name.
    if: ( github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: BE transaction-service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8 # Give the value at most 8 mins.
    defaults:
      run:
        working-directory: backend/transaction-service # Change the working-directory to your microservice folder name.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better relevancy of analysis.

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu" # Alternative distribution options are available.

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.TRANSACTION_SERVICE_TOKEN }} # Change the token name accordingly.
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bootcamp-be-105-business-service -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} -Dsonar.pullrequest.key=${{github.event.pull_request.number}} # Change the projectName and projectKey accordingly.
